brew "postgresql"
brew "watchman"
brew "nvm"

# I think this will do the equivalent of brew install --cask docker
# You probably have to actually run the docker application after that installs for "which docker"
# to show anything
#cask "docker"