name: Build, Test, and Lint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  NODE_VERSION: '12.16.1'
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  build-test-and-lint:
    runs-on: ubuntu-latest
    environment: test-environment
    steps:
    
      - name: Notify slack started
        id: slack # IMPORTANT: reference this step ID value in future Slack steps    
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: github-actions
          status: STARTED
          color: warning
          
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install node modules
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present
      - name: Lint
        run: npm run lint --if-present
      - run: echo "Job status - ${{ job.status }}"
      
      - name: Notify slack success
        if: success()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: SUCCESS
          color: good
          
      - name: Notify slack failure
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-actions
          status: FAILED
          color: danger
