name: Build, Test, and Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  NODE_VERSION: '12.16.1'

jobs:
  build-test-and-lint:
    runs-on: ubuntu-latest
    environment: test-environment
    steps:
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install node modules
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present
      - name: Lint
        run: npm run lint --if-present
      - run: echo "Job status - ${{ job.status }}"
