name: Test and Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  NODE_VERSION: '12.16.1'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, test and lint
        run: |
          # Build test and lint the project
          npm install
          npm run build --if-present
          npm run test --if-present
          npm run lint --if-present
      - run: echo "Job status - ${{ job.status }}"
